[profile.default]
# 2519: Shadowing (you named a local variable the same as a return variable)
# 5667: Unused parameter (like performData)
# 2424: Deprecated Natspec (usually in external libs like Chainlink)
ignored_error_codes = [2519, 5667, 2424]

src = "src"
out = "out"
libs = ["lib"]
# To disable specific linting rules
[lint]
ignored = [
    "mixed-case-variable",
    "mixed-case-function",
    "unwrapped-modifier-logic",
]

# OR: To disable the linter completely
lint = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
